name: test

on:
  - push

jobs:
  karma-ios:
    name: karma by iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: xcrun simctl list
      - run: xcrun simctl list -j
      - run: |
          xcrun simctl list -j | jq '.devices[][] | select(.isAvailable == true) | { (.name): .udid }' | jq -s add
      - run: |
          xcrun simctl list -j | jq '.devices[][] | select(.isAvailable == true) | { (.name): .udid }' | jq -s add | jq -r '.["iPhone 11"]' | tee udid
      - run: xcrun simctl boot $(cat udid)
      - run: xcrun simctl openurl $(cat udid) http://127.0.0.1:9876 &
      - run: yarn karma start --single-run --no-browsers
      - run: xcrun simctl io $(cat udid) screenshot ./screenshot.png
      - uses: actions/upload-artifact@v1
        with:
          name: screenshot.png
          path: screenshot.png
