name: test

on:
  - push

jobs:
  karma-ios:
    name: karma by iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: xcrun simctl list
      - run: xcrun simctl boot 21A66C1C-E521-4FA4-BBF4-A371733DEC8A
      - run: (sleep 3 && xcrun simctl openurl 21A66C1C-E521-4FA4-BBF4-A371733DEC8A http://127.0.0.1:9876) &
      - run: yarn karma start --single-run --no-browsers
      - run: xcrun simctl io 21A66C1C-E521-4FA4-BBF4-A371733DEC8A screenshot ./screenshot.png
      - uses: actions/upload-artifact@v1
        with:
          name: screenshot.png
          path: screenshot.png
